version: '2'
services:
  web:
    build: .
    expose:
      - "5555"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=clicker.piti.me,www.clickery.org,clickery.org
      - LETSENCRYPT_HOST=clicker.piti.me,www.clickery.org,clickery.org
      - LETSENCRYPT_EMAIL=piti118@gmail.com
    network_mode: "bridge"
