version: '2'
services:
  web:
    build: .
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=clicker.piti.me
      - LETSENCRYPT_HOST=clicker.piti.me
      - LETSENCRYPT_EMAIL=piti118@gmail.com
    network_mode: "bridge"